n1c0_dissertation_dissertation:
    type: rest
    prefix: /v1
    resource: N1c0\DissertationBundle\Controller\DissertationController
    name_prefix:  api_1_ # naming collision

n1c0_dissertation_argument:
    type: rest
    parent: n1c0_dissertation_dissertation
    resource: N1c0\DissertationBundle\Controller\ArgumentController
    name_prefix:  api_1_ # naming collision

n1c0_dissertation_introduction:
    type: rest
    parent: n1c0_dissertation_dissertation
    resource: N1c0\DissertationBundle\Controller\IntroductionController
    name_prefix:  api_1_ # naming collision

n1c0_dissertation_logs:
    type: rest
    parent: n1c0_dissertation_dissertation
    resource: N1c0\DissertationBundle\Controller\LogController
    name_prefix:  api_1_ # naming collision
